version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - database
    env_file:
      - .env.docker
    volumes:
      - .:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database

  web:
    image: nginx:1.15
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - ./dev/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: foodchoose
      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - 43306:3306

volumes:
  database-volume:
